export const mealOptions = [
  { id: 1, name: "Pancakes" },
  { id: 2, name: "Green Salad" },
  { id: 3, name: "Pasta" },
  { id: 4, name: "Pizza" },
  { id: 5, name: "Chicken Soup" },
  { id: 6, name: "Fruits Salad" },
  { id: 7, name: "Icecream" },
  { id: 8, name: "French Fries" },
  { id: 9, name: "Fish and Chips" },
  { id: 10, name: "Beef Steak" },
  { id: 11, name: "Meat Balls" },
  { id: 12, name: "Vegetable Soup" },
  { id: 13, name: "Cacao Cake" },
];
